set(CPACK_PACKAGE_NAME
    ${CMAKE_PROJECT_NAME}
    CACHE STRING "Output package name"
)

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY
    "mhz: measure your clock speed, reliably, cross-architecture"
    CACHE STRING "Package description for the package metadata"
)
set(CPACK_PACKAGE_VENDOR "neggles.dev")
set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
SET(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_SOURCE_DIR}/dist")

set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")

set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

set(CPACK_PACKAGE_CONTACT "neggles@neggles.dev")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Andi Powers-Holmes")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.md")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)

set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE)

include(CPack)
